# Generated by Django 3.2 on 2021-04-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='lineid',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
